name             'autopatch-nativex'
maintainer       'NativeX'
maintainer_email 'derek.bromenshenkel@nativex.com'
license          'All rights reserved'
description      'Installs/Configures autopatch-nativex'
long_description 'Installs/Configures autopatch-nativex'
version          '0.1.0'

depends 'auto-patch', '=0.1.9'
depends 'windows', '=1.37.0'
