name             'autopatch-simplyadrian'
maintainer       'simplyadrian'
maintainer_email 'simplyadrian@gmail.com'
license          'All rights reserved'
description      'Installs/Configures autopatch-simplyadrian'
long_description 'Installs/Configures autopatch-simplyadrian'
version          '1.1.0'

depends 'auto-patch'
depends 'logrotate'
depends 'windows'
