name             'autopatch-nativex'
maintainer       'NativeX'
maintainer_email 'derek.bromenshenkel@nativex.com'
license          'All rights reserved'
description      'Installs/Configures autopatch-nativex'
long_description 'Installs/Configures autopatch-nativex'
version          '1.0.0'

depends 'auto-patch'
depends 'logrotate'
depends 'windows'
